# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: publish on version change
      id: publish_nuget
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: GameAssetArchive/GameAssetArchive.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
